export enum GooglePhoneNumberLabel {
  HOME = "HOME",
  WORK = "WORK",
  MOBILE = "MOBILE",
  HOMEFAX = "HOMEFAX",
  WORKFAX = "WORKFAX",
  OTHERFAX = "OTHERFAX",
  PAGER = "PAGER",
  WORKMOBILE = "WORKMOBILE",
  WORKPAGER = "WORKPAGER",
  MAIN = "MAIN",
  GOOGLEVOICE = "GOOGLEVOICE",
  OTHER = "OTHER",
}
